### ISSUE TITLE
drracket doesn't seem to launch

### ISSUE THREAD

**Issue by carnage-mode** [flathub/org.racket_lang.Racket#2]
Clicking the desktop icon doesnt work. I even tried the `flatpak run --command=drracket org.racket_lang.Racket` command and nothing seems to work

**Comment by carnage-mode** [comment]
racket it self works fine though

**Comment by capfredf** [comment]
what's the output of `flatpak run --command=racket org.racket_lang.Racket -l drracket`?

BTW, what's your distro?

**Comment by carnage-mode** [comment]
> what's the output of `flatpak run --command=racket org.racket_lang.Racket -l drracket?`

It shows the DrRacket load screen but nothing happens when the load screen disappears. The loading screen stayed for a while though.

> BTW, what's your distro?

Fedora Silverblue

**Comment by capfredf** [comment]
I am unable to reproduce this issue on a SilverBlue instance on a virtual machine
![image](https://user-images.githubusercontent.com/512906/215384949-cc652afc-1553-48f9-9067-0e2a991a2b65.png)


> > what's the output of `flatpak run --command=racket org.racket_lang.Racket -l drracket?`
> 
> It shows the DrRacket load screen but nothing happens when the load screen disappears. The loading screen stayed for a while though.

Were there any messages or logs shown at the command line?

**Comment by carnage-mode** [comment]
> Were there any messages or logs shown at the command line?

Nothing. I have drracket installed in a toolbox container and it works fine. Maybe the one in toolbox is messing with the flatpak version? I know that this shouldn't happen because of sand boxing

**Comment by carnage-mode** [comment]
I believe this might be a memory leak. Look at this 
[Screencast from 2023-02-01 18-37-45.webm](https://user-images.githubusercontent.com/69735963/216089765-7b970f88-dcfe-4058-8650-c96372d8704e.webm)

It randomly crashes after running for a couple seconds

**Comment by carnage-mode** [comment]
Okay it got it running, but it takes way too long. Multiple minutes

**Comment by VosaXalo** [comment]
> Okay it got it running, but it takes way too long. Multiple minutes

Same here. I'm on KDE Neon 22.04 (_installed, not virtual machine_), and DrRacket takes several minutes to start. 
I have tried **the snap package** and it works much better. It **starts in seconds**.

**Comment by jntdofe** [comment]
Can confirm the slow startup (Fedora Silverblue 37).
I had to use Toolbox instead.
It takes around 1.5 minutes to make a window appear and another two to load the editor.
With toolbox it takes less than 5 seconds.

**Comment by capfredf** [comment]
I did some digging. I have installed the latest Flatpak racket on Fedora 37 and Fedora 38 in two VirtualBox instances. The one on F37 is indeed super slow (e.g., it takes more than 3 mins to launch DrRacket), but the one on F38 is as fast as the racket from the linux installer from the official website. 

It is unclear to me that which part causes the performance issue on Fedora 37 or other distro you guys have the problem on. It might be that older versions of flatpak have some performance issues, or Racket does not work well with some of their components.   

I will need to ask around in the flatpak community and see if I can work this issue out.

**Comment by Antigen-1** [comment]
> The one on F37 is indeed super slow (e.g., it takes more than 3 mins to launch DrRacket)

I tried `flatpak run org.racket_lang.Racket` on Ubuntu 22.04 and it turned out to be a drracket instance, which is rather slow too.

**Comment by Antigen-1** [comment]
And After launching drracket, I got an error like this:
```
/app/share/racket/pkgs/errortrace-lib/errortrace/private/utils.rkt:34:14: begin: unbound identifier;
 also, no #%app syntax transformer is bound
  at: begin
  in: (begin (#%require (for-meta 1 drracket/private/drracket-errortrace-key)) (#%require (for-meta 0 drracket/private/drracket-errortrace-key)))
  context...:
   #(-869346 module utils) #(-841317 module) [common scopes]
  other binding...:
   #(begin #<module-path-index:'#%core> 0)
   #(869034 module) #(869037 module runtime-reflect) [common scopes]
  common scopes...:
   #(869341 module) #(869344 module runtime-reflect)
```

**Comment by capfredf** [comment]
> I tried `flatpak run org.racket_lang.Racket` on Ubuntu 22.04 and it turned out to be a drracket instance, which is rather slow to

if you want to run racket at the command line, you can run `flatpak run --command=racket org.racket_lang.Racket`. 
Making the default command `drracket` is necessary to launch a drracket by clicking the open button in `gnome software`. Maybe there is a way to write a wrapper script so that we can tell whether it is run from the command line or from somewhere else.

**Comment by Sunspark-007** [comment]
Earlier I was reading this thread https://bbs.archlinux.org/viewtopic.php?id=285590 about xdg-desktop-portal and xdg-desktop-portal-gnome failing and causing packages to load slowly.

Made me wonder. Does this flatpak use those packages? I took a look at version numbering and Fedora 37 uses 43.1 while Fedora 38 uses 44.0. Thread states that downgrading to 43 or removing the package fixed the problems.

Maybe this is a possible contributor?

**Comment by Sunspark-007** [comment]
Curious to see if a refreshed flatpak to Racket 8.10 with all-new dependencies will fix the slow-launch issue.

**Comment by carnage-mode** [comment]
> Curious to see if a refreshed flatpak to Racket 8.10 with all-new dependencies will fix the slow-launch issue.

Seems to work fine now! Closing the issue

**Comment by Sunspark-007** [comment]
Tested it yesterday. Confirmed as launching normally on the same SteamOS system that 8.9 wasn't launching properly on. Thanks!

If you are able to share, I'm curious to know what the issue was.. was it a dependency that just fixed things on its own via update to a newer version, or did you have to do something in terms of packaging or something else?

**Comment by capfredf** [comment]
I think it had something to do with older versions of the `flatpak` lib. I haven't changed anything except for the checksums and download URL. 

On my Tumbleweed and Aeon machines, the flatpak Racket has been as (almost) fast as versions installed via the official installer and `zypper` since I started packaging it. I didn't notice the obnoxious slowness until the issue popped up. This is mainly because those two distros are rolling released and the `flatpak` lib is always up to date unlike in other point-released distros.
